### ISSUE TITLE
Test-mr.sh not working on tested systems

### ISSUE THREAD

**Issue by feanors** [arindas/mit-6.824-distributed-systems#1]
On the systems I've tested (Ubuntu 22.04 and Ubuntu 20.04 on wsl2) test-mr.sh fails for early_exit with the following error:

test-mr.sh: 205: wait: Illegal option -n

Googling the error led me to this: https://github.com/ahmetb/cloud-run-static-outbound-ip/issues/2 , which an answer mentions "wait" command doesn't take -n flag these days

I'll be doing a pull request shortly with an alternative solution.

This is my first time ever posting an issue or a pull request, so I hope I didn't butcher any guidelines or anything.

**Comment by arindas** [comment]
Thanks for testing this out. I'll be awaiting your PR

**Comment by feanors** [comment]
Hey, thank you for responding.

I've sent the PR. I was too excited on my first contribution ever thus I forgot to add some explanatory comments :D

If needed I can send another PR with comments describing the changes, but it's a fairly simple code and probably not the most optimal solution.

**Comment by arindas** [comment]
Some comments would indeed be better.
